import axios from "axios";
export const REMOTE_SERVER = import.meta.env.VITE_REMOTE_SERVER;
export const WORDLES_EXTERNAL_API = `${REMOTE_SERVER}/api/wordle-api`;
export const WORDLES_API = `${REMOTE_SERVER}/api/wordles`; // Internal API for wordles generated by our app
export const WORDLE_GUESSES_API = `${REMOTE_SERVER}/api/wordle-guesses`; // Internal API for wordle guesses made by our app
const axiosWithCredentials = axios.create({ withCredentials: true });

export const getWordleByDay = async (day: string) => {
  const response = await axiosWithCredentials.get(
    `${WORDLES_EXTERNAL_API}/${day}`
  );
  return response.data;
};

export const getUserWordleGuessesByDate = async (date: string) => {
  const response = await axiosWithCredentials.get(
    `${WORDLE_GUESSES_API}/user/date/${date}`
  );
  return response.data;
};

export const updateUserWordleGuessByDate = async ({
  createdDate,
  guesses,
  completed,
}: {
  createdDate: string;
  guesses: string[];
  completed: boolean;
}) => {
  await axiosWithCredentials.patch(`${WORDLE_GUESSES_API}`, {
    createdDate,
    guesses,
    completed
  });
};

export const getWordleGuessesByDay = async (day: string) => {
  const response = await axiosWithCredentials.get(
    `${WORDLE_GUESSES_API}/user/date/${day}`
  );
  return response.data;
}