import axios from "axios";
import { Wordle } from "./CustomWordles/CreateWordleModal";
export const REMOTE_SERVER = import.meta.env.VITE_REMOTE_SERVER;
export const WORDLES_EXTERNAL_API = `${REMOTE_SERVER}/api/wordle-api`;
export const WORDLES_API = `${REMOTE_SERVER}/api/wordles`; // Internal API for wordles generated by our app
export const WORDLE_GUESSES_API = `${REMOTE_SERVER}/api/wordle-guesses`; // Internal API for wordle guesses made by our app
const axiosWithCredentials = axios.create({ withCredentials: true });

export const getWordleByDay = async (day: string) => {
  const response = await axiosWithCredentials.get(
    `${WORDLES_EXTERNAL_API}/${day}`
  );
  return response.data;
};

export const getUserWordleGuessesByDate = async (date: string) => {
  const response = await axiosWithCredentials.get(
    `${WORDLE_GUESSES_API}/user/date/${date}`
  );
  return response.data;
};

export const updateUserWordleGuessByDate = async ({
  createdDate,
  guesses,
  completed,
  timeSpent,
}: {
  createdDate: string;
  guesses: string[];
  completed: boolean;
  timeSpent: number;
}) => {
  await axiosWithCredentials.patch(`${WORDLE_GUESSES_API}`, {
    createdDate,
    guesses,
    completed,
    timeSpent,
  });
};

export const getWordleGuessesByDay = async (day: string) => {
  const response = await axiosWithCredentials.get(
    `${WORDLE_GUESSES_API}/date/${day}`
  );
  return response.data;
};

export const getWordleGuessesByWorldeId = async (wordleId: string) => {
  const response = await axiosWithCredentials.get(
    `${WORDLE_GUESSES_API}/wordleId/${wordleId}`
  );
  return response.data;
};

export const getAllCustomWordles = async (query = {}) => {
  const queryString = Object.entries(query)
    .map(([key, value]) => `${key}=${value}`)
    .join("&");
  const response = await axiosWithCredentials.get(
    `${WORDLES_API}${queryString ? `?${queryString}` : ""}`
  );
  return response.data;
};

export const getWordleByWordleId = async (wordleId: string) => {
  const response = await axiosWithCredentials.get(`${WORDLES_API}/${wordleId}`);
  return response.data;
};

export const getUserWordleGuessesByWordleId = async (wordleId: string) => {
  const response = await axiosWithCredentials.get(
    `${WORDLE_GUESSES_API}/user/wordleId/${wordleId}`
  );
  return response.data;
};

export const updateUserWordleGuessByWordleId = async ({
  wordleId,
  guesses,
  completed,
  timeSpent,
}: {
  wordleId: string;
  guesses: string[];
  completed: boolean;
  timeSpent: number;
}) => {
  await axiosWithCredentials.patch(`${WORDLE_GUESSES_API}/custom`, {
    wordleId,
    guesses,
    completed,
    timeSpent,
  });
};

export const createCustomWordle = async (wordle: Wordle) => {
  const response = await axiosWithCredentials.post(`${WORDLES_API}`, wordle);
  return response.data;
};

export const updateCustomWordle = async (wordle: Wordle) => {
  const response = await axiosWithCredentials.patch(
    `${WORDLES_API}/${wordle._id}`,
    wordle
  );
  return response.data;
};

export const deleteCustomWordle = async (wordleId: string) => {
  await axiosWithCredentials.delete(`${WORDLES_API}/${wordleId}`);
}
